# Generated by Django 4.2.1 on 2023-05-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'permissions': (('can_mark_returned', 'Set book as returned'), ('can_renew', 'Can renew Borrwed Book'))},
        ),
    ]
